#!/usr/bin/env php
<?php
include("airavata.php");
if ($argc == 3) {
        $appId = $argv[1];
        $json = $argv[2];
        $projId=createProject("admin", $appId);
        // echo var_dump($projId);
        $expId=createExperiment("admin", "exp5", $projId, $appId, $json); 
		// $expId =  "exp5_e7b826cf-a429-4b3e-b519-28d859fe4b64";
		// echo var_dump($expId);
		$res = launchExperiment($expId);
		// echo var_dump($res); 
		while(($status=get_experiment_status($expId))!="COMPLETED"){    
			// echo "$status\n";
			sleep(1);
		}
		echo getOutput($expId);

    } else {
       echo  "{\"error\":\"insufficient arguments\"}";
	}
?>